
import { useExecutionStore } from '../../store/executionStore';
import { Sparkles } from 'lucide-react';

export default function BeginnerExplanationPanel() {
    const { traces, currentStepIndex, analysis } = useExecutionStore();

    // Safety check
    if (!traces || traces.length === 0 || currentStepIndex < 0 || currentStepIndex >= traces.length) {
        return null; // Or return a "Ready" state
    }

    const currentTrace = traces[currentStepIndex];

    // Look up AI explanation for this line if available
    const lineNo = currentTrace.line;
    const aiExplanation = analysis?.explanation?.[lineNo.toString()];

    // Fallback to trace explanation (technically generated by backend executor)
    const explanation = aiExplanation || currentTrace.explanation;

    return (
        <div className="bg-bg-panel border-t border-border-subtle p-4 flex items-start gap-4 animate-slide-up">
            <div className="bg-accent-purple/10 p-2 rounded-full mt-1">
                <Sparkles className="w-5 h-5 text-accent-purple" />
            </div>
            <div className="flex-1">
                <h3 className="text-sm font-bold text-text-primary mb-1 uppercase tracking-wide opacity-70">
                    Step {currentStepIndex + 1}
                </h3>
                <p className="text-lg text-white leading-relaxed font-medium">
                    {explanation}
                </p>
                {/* Contextual Hint (e.g. Variable update) */}
                {currentTrace.type === 'assignment' && (
                    <div className="mt-2 flex items-center gap-2 text-sm text-text-muted bg-bg-main/50 px-3 py-1.5 rounded-md w-fit">
                        <span className="w-2 h-2 rounded-full bg-accent-green"></span>
                        Variable Updated
                    </div>
                )}
                {currentTrace.type === 'condition' && (
                    <div className="mt-2 flex items-center gap-2 text-sm text-text-muted bg-bg-main/50 px-3 py-1.5 rounded-md w-fit">
                        <span className="w-2 h-2 rounded-full bg-accent-orange"></span>
                        Making a decision
                    </div>
                )}
            </div>
        </div>
    );
}
